name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted   # usar o runner que criaste

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add server to known_hosts (opcional)
        run: |
          ssh-keyscan -p 2822 -H 172.17.100.11 >> ~/.ssh/known_hosts || true

      - name: Deploy to server
  run: |
    ssh -p 2822 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
      cd /opt/back-Portal-denucias || exit 1
      git pull origin main
      docker compose pull
      docker compose up -d --build
      docker system prune -f
    EOF

