name: Deploy Automático

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/keepcomply
            git pull origin main
            docker exec portalReclamacoes-php composer install --no-dev --optimize-autoloader
            docker exec portalReclamacoes-php php artisan migrate --force
            docker exec portalReclamacoes-php php artisan config:cache
            docker exec portalReclamacoes-php php artisan route:cache
            docker exec portalReclamacoes-php php artisan view:cache